### ISSUE TITLE
Remove example code dependencies

### ISSUE THREAD

**Issue by acgaudette** [cogciprocate/voodoo#2]
`hello.rs` imports a few crates that are not used in the core library.
Definitely `cgmath`, and also `tobj`, `image`, and `ordered_float` I think?

See [doc.crates.io/specifying-dependencies.html#development-dependencies]()

**Comment by c0gent** [comment]
You're right. I'll clean those up tomorrow or the next day.

**Comment by c0gent** [comment]
f31290fe54116e8b6359ecb237e105f9789e3aef

Thanks for catching this :)

**Comment by acgaudette** [comment]
Hey, you mind updating this on crates.io? :D

**Comment by c0gent** [comment]
No problem :)

Since you're here, I hope you don't mind if I pick your brain for some opinions...

What else do you think we can do make this library better? What do you think of renaming builders as mentioned in #1? Are there any other ergonomic improvements you can think of?

**Comment by acgaudette** [comment]
Using it [here](https://github.com/acgaudette/nmg-vulkan/blob/master/src/render.rs). There are a couple of small things I'll try and make PRs for later when I get some time. Overall have enjoyed the API so far. Don't have much to comment on structs versus builders--the builders seem to make sense given that you deviate from the original C structs in minor ways, and allow for default values. I haven't used e.g. ash so I don't know what the alternative feels like in Rust.

**Comment by acgaudette** [comment]
No worries. The documentation doesn't bother me since it's very close to the spec. The only potential hangups are where it differs/the abstraction is unclear.

**Comment by c0gent** [comment]
Yes, please point out those areas when you run up against them if you would. I definitely have a blind spot for what is or isn't clear.
